# install dependencies
FROM node:lts AS base
WORKDIR /usr/src/app

COPY package*.json .
RUN npm install

COPY . .

ARG URL_MONGODB
ARG PORT
ARG SALT
ARG SECRET_ACCESSTOKEN
ARG SECRET_REFRESHTOKEN
ARG SECRET_EMAIL
ARG PASSWORD_EMAIL
ARG URL_FRONTEND
ARG URL_POPULARBOARDGAME
ARG URL_CLOUDSTORAGE
ARG URL_SERVICE_MODEL
ARG PORT_MODEL

ENV URL_MONGODB=${URL_MONGODB}
ENV PORT=${PORT}
ENV SALT=${SALT}
ENV SECRET_ACCESSTOKEN=${SECRET_ACCESSTOKEN}
ENV SECRET_REFRESHTOKEN=${SECRET_REFRESHTOKEN}
ENV SECRET_EMAIL=${SECRET_EMAIL}
ENV PASSWORD_EMAIL=${PASSWORD_EMAIL}
ENV URL_FRONTEND=${URL_FRONTEND}
ENV URL_POPULARBOARDGAME=${URL_POPULARBOARDGAME}
ENV URL_CLOUDSTORAGE=${URL_CLOUDSTORAGE}
ENV URL_SERVICE_MODEL=${URL_SERVICE_MODEL}

RUN npm install -g typescript
RUN npm run build

EXPOSE 5000
CMD [ "npm", "run", "start:docker" ]


